### ISSUE TITLE
Unable to install docker-compose

### ISSUE THREAD

**Issue by magnida** [weareinteractive/ansible-docker-compose#3]
Hi I am getting the following issue on a target node that I am trying to install docker-compose on. After it is installed with this role, a docker-compose --version will output this:

foo@js-1094-d:~$ docker-compose --version
**WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker**
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 20, in <module>
    from ..bundle import get_image_digests
  File "/usr/local/lib/python2.7/dist-packages/compose/bundle.py", line 13, in <module>
    from .network import get_network_defs_for_service
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 7, in <module>
    from docker.types import IPAMConfig
ImportError: cannot import name IPAMConfig

Running with 1.2.2 (latest at the time) for the compose role and Ansible 2.3.1 with this snippet from the playbook:

vars:
    docker_compose_version: 1.14.0
  roles:
    - franklinkim.docker
    - franklinkim.docker-compose

Any ideas?

Thanks

**Comment by franklinkim** [comment]
Hi, what platform are you running on (i.e. Ubuntu Xenial)?

**Comment by franklinkim** [comment]
Just ran the vagrant box test and I see the same error. 
Unfortunately my docker role is not up to date with the new docker CE version installation. 
Any PRs would be appreciated!

**Comment by magnida** [comment]
@franklinkim  I also noticed that the v1.9.0 version isn't on Ansible Galaxy(latest is 1.7.0). Would it be possible to add it, so that I can test on CentOS?

**Comment by franklinkim** [comment]
@magnida sure, somehow the travis webhook doesn't seem to reach ansible.. manually updated the role
